title: Blog Informático
author:
  name   : "Adrián Rodríguez Povea"
  avatar : "/_images/logo.PNG"
  bio    : "Blog Informático"
  email  : "arodriguezpovea@gmail.com"
  github : "arpovea"
  twitter : "arodriguezpovea"
  location: "Dos Hermanas, Sevilla,ES" # null (default), "absolute or relative url to link to author home"

description: > # this means to ignore newlines until "show_excerpts:"
  “La tecnología por sí sola no basta. También tenemos que poner el corazón” – Jane Goodall
  
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://www.arpovea.github.io" # the base hostname & protocol for your site


  # generate social links in footer
  social_links:
    twitter: arodriguezpovea
    github:  arpovea
    # rss: rss
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

timezone: Europe/Madrid
locale: "es-ES"
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
